### ISSUE TITLE
Failed to create daemon	(insufficient privileges)

### ISSUE THREAD

**Issue by danilaplee** [stv0g/cunicu#120]
<img width="699" alt="Screenshot 2022-12-08 at 04 58 18" src="https://user-images.githubusercontent.com/6561396/206330135-61ef5b48-2437-45e3-8641-d28f039caad2.png">
<img width="491" alt="Screenshot 2022-12-08 at 04 58 46" src="https://user-images.githubusercontent.com/6561396/206330202-0feda0ae-381c-48e0-a498-8ec7684cae42.png">
<img width="697" alt="Screenshot 2022-12-08 at 05 18 12" src="https://user-images.githubusercontent.com/6561396/206332459-68d25e63-ce95-4cf0-b898-1e91347c1c5a.png">

wireguard is installed as you may see 
the system is darwin 13.0.0
i'am running sudo as you may see and wireguard as well as cunicu are installed using the brew distro

I would like to embed cunicu in my webtorrent streaming app

**Comment by stv0g** [comment]
Hi @danilaplee,

thanks for reporting the issue. I would mention that cunicu isnt really ready for prime time yet.
But you are very welcome to report issues and support me in getting it ready for its first release :)

The code in question which checks for the required permissions can be found here:

https://github.com/stv0g/cunicu/blob/965a21736f114e0d831b965305215c8eb411c2a9/pkg/util/capabilities_bsd.go#L10

For BSD's (which also applies to Darwin/macOS we just check if cunicu has been executed by the root user.

I will change the check to use the effective user id (`os.Geteuid()`).
But I doubt that this has been the issue for you.

Can you please verify if you are running cunicu really with superuser privileges?
E.g. running the `id` command in the same shell as cunicu?

**Comment by danilaplee** [comment]
<img width="696" alt="Screenshot 2022-12-08 at 16 37 35" src="https://user-images.githubusercontent.com/6561396/206448363-32c6b9e1-feb3-4f38-9281-03f3c8a85e11.png">
done

**Comment by danilaplee** [comment]
can i already test the latest build somewhere?

**Comment by stv0g** [comment]
Hi @danilaplee,

I can not reproduce your issue with the latest version cunicu on my macOS machine.

> can i test the latest build somewhere?

I just published a new release (v0.2.5) which you can install via the standard methods as described here:

http://cunicu.li/docs/install

You could also try cunicus built-in self-update functionality by running

```bash
cunicu selfupdate
```

**Comment by danilaplee** [comment]
selfupdate produced the next output:
<img width="959" alt="Screenshot 2022-12-10 at 23 48 12" src="https://user-images.githubusercontent.com/6561396/206872810-321bb67b-fb2a-43de-aed8-54fc78050824.png">
i was able to update using brew anyway
<br>
looks like cunicu did run:
<img width="941" alt="Screenshot 2022-12-10 at 23 48 57" src="https://user-images.githubusercontent.com/6561396/206872834-61262a92-ce30-4c41-a29b-a594e716b3cb.png">

<br>
but I'am not able to use any commands
<img width="792" alt="Screenshot 2022-12-10 at 23 51 19" src="https://user-images.githubusercontent.com/6561396/206872902-5e5d5dbe-3ad6-4300-8ce6-bb09de3ac391.png">

**Comment by danilaplee** [comment]
oh looks like the problem was i had to run all comands also as sudo

**Comment by stv0g** [comment]
Just a note: you will need to either have a pre-existing WireGuard interface existing, or start cunicu with one or more names of interfaces which should be created:

```bash
sudo cunicu daemon wg0
```

Otherwise, the daemon will just wait until a new interface has been created by the user.
