### ISSUE TITLE
Create Nix package

### ISSUE THREAD

**Issue by stv0g** [stv0g/cunicu#145]
Do we have some Nix users around who could create a package?

**Comment by Iamhero337** [comment]
Hey, I am just trying to contribute to open source.

**If it doesn't require a lot of learning and time then I can do it.** 
Just guide me a little.

**Comment by bmullan** [comment]
just a comment on NixOS...  the project has some strong headwinds with their AWS S3 costs and lost their Sponsor for those "costs".    May put the project in jeopardy.

https://discourse.nixos.org/t/the-nixos-foundations-call-to-action-s3-costs-require-community-support/28672

**Comment by stv0g** [comment]
Hi @bmullan,

I yeah I've also read the call to action in their community.
But I dont expect that this will harm the project or its adoption considerably.

Not being a Nix user myself, I cant say for sure.. But I think the S3 buckets are mainly used by https://cache.nixos.org for caching pre-built binaries. However, one of the strengths of Nix is also its capability to fully rebuild itself from its package definitions. Hence, the cache is probably not as crucial as it seems..

**Comment by stv0g** [comment]
For cunicu, the best way to provide a Nix package is probably via GoReleaser's built-in support for Nixpkgs.

See: https://goreleaser.com/customization/nix/
