### ISSUE TITLE
Is cunīcu still considered in Alpha state?

### ISSUE THREAD

**Issue by bmullan** [stv0g/cunicu#166]
Is cunicu still considered in Alpha state?

If so, what would you say are the "gating" factors to enter "beta".

thanks

**Comment by stv0g** [comment]
Hi @bmullan,

yes cunicu is currently still needs to be considered as an experimental tool. I've added a extra warning to the `cunicu daemon` command to make this very clear. Basic tests are succeeding in our integration tests. However, I have conducted limited tests in real network environments.

I've started to create milestones in GitHubs issue tracker to keep track of the progress:
- [First stable release (v1.0)](https://github.com/stv0g/cunicu/milestone/1)
- [First beta release (v0.5)](https://github.com/stv0g/cunicu/milestone/2)

Please have a look at the milestones to see what is missing for the first beta version.

Nevertheless, I encourage everybody to give it a try and report your issues :)
I am eager to fix connectivity issues if they arrise!
